- name: Configure Layer 2
  hosts: all
  gather_facts: no
  connection: local

  roles:
    - role: arista.eos

  tasks:
    - name: Create VLANs
      eos_vlan: vlanid={{ item.vlan_id }} name={{ item.name }} trunk_groups={{ item.trunk_group }} connection="{{ inventory_hostname }}"
      with_items: "{{ vlans_create | default([]) }}"
    - name: Create Port-channels
      eos_portchannel: name={{ item.portchannel }} members={{ item.members }} lacp_mode={{ item.lacpmode }} connection="{{ inventory_hostname }}"
      with_items: "{{ portchannels_create | default([]) }}"
    - name: Configure Switchport settings
      eos_switchport: name={{ item.switchport }} mode={{ item.mode }} trunk_groups={{ item.tg }} connection="{{ inventory_hostname }}"
      with_items: "{{ switchports | default([]) }}"

- name: Configure Layer 3
  hosts: all
  gather_facts: no
  connection: local

  roles:
  - role: arista.eos

  tasks:
  - name: Enables IP routing
    eos_system: ip_routing=yes connection={{ inventory_hostname }}

  - name: Create Loopbacks and SVIs
    eos_interface: name={{ item.interface }} state=present enable=yes connection={{ inventory_hostname }}
    with_items: "{{ interfaces_create | default([]) }}"

  - name: Configure IP Addresses
    eos_ipinterface: name={{ item.interface }} state=present address={{ item.ip}} connection={{ inventory_hostname }}
    with_items: "{{ interfaces_ip | default([]) }}"

- name: Configure MLAG on leaf switches
  hosts: leaf_switches
  gather_facts: no
  connection: local

  roles:
  - role: arista.eos

  tasks:
    - name: Configure MLAG domain-id
      eos_mlag_config: domain_id={{ mlag_domain_id }} connection={{ inventory_hostname }}
    - name: Configure the peer address, peer-link and local interface
      eos_mlag_config: peer_address={{ mlag_peer_ip }} local_interface=Vlan4094 peer_link=Port-Channel1 connection={{ inventory_hostname }}

    - name: Create MLAGs
      eos_mlag_interface: name={{ item.mlag_members }} state=present mlag_id={{ item.mlag_id }} connection={{ inventory_hostname }}
      with_items: "{{ mlags_create | default([]) }}"

    - name: Configure MLAG switchport parameters
      eos_switchport: name={{ item.portchannel }} mode=trunk trunk_groups= {{ item.tg }} connection="{{ inventory_hostname }}"
      with_items: "{{ mlag_switchports | default([]) }}"

- name: Configure BGP routing
  hosts: all
  gather_facts: no
  connection: local

  roles:
  - role: arista.eos

  tasks:
  - name: enable BGP routing
    eos_bgp_config: bgp_as={{ bgp_as }} state=present enable=yes router_id={{ bgp_rid }} connection={{ inventory_hostname }}
  - name: configure BGP neighbors
    eos_bgp_neighbor: name={{ item.bgp_peer_ip }} enable=yes remote_as={{ item.bgp_peer_as }} connection={{ inventory_hostname }}
    with_items: "{{ bgp_neighbors | default([]) }}"
  - name: configure BGP network advertisements
    eos_bgp_network: prefix={{ item.bgp_net }} masklen={{ item.bgp_mask }} connection={{ inventory_hostname }}
    with_items: "{{ bgp_networks | default([]) }}"

- name: Configure VXLAN on leaf switches
  hosts: leaf_switches
  gather_facts: no
  connection: local

  roles:
  - role: arista.eos

  tasks:
    - name: Configure VXLAN interface
      eos_vxlan: name=Vxlan1 state=present enable=yes source_interface=Loopback1 connection={{ inventory_hostname }}
    - name: create a new vlan to vni mapping
      eos_vxlan_vlan: name=Vxlan1 state=present vlan={{item.vlan }} vni={{ item.vni }} connection={{ inventory_hostname }}
      with_items: "{{ vxlan_vni }}"
    - name: Ensures that VTEPs are in the global flood list
      eos_vxlan_vtep: name={{ item.vtep }} state=present vtep={{ item.flood_list }} connection={{ inventory_hostname }}
      with_items: "{{ vxlan_floodlist }}"
